name:                 eta-service
version:              0.1.0.0
visibility:           public
id:                   eta-service-0.1.0.0-K0aOwEi25BS9pYwtd4gwNr
key:                  eta-service-0.1.0.0-K0aOwEi25BS9pYwtd4gwNr
synopsis:
    Standalone ETA / route estimation service for the Mini Ride-Dispatch Simulator

abi:                  3f1ff81075b78c8fa4b135bfdff627fd
exposed:              True
exposed-modules:      Eta
hidden-modules:       Paths_eta_service
import-dirs:
    C:\Users\HP\Desktop\Ride_Dispatch\eta_service\.stack-work\install\c84bbe0f\lib\x86_64-windows-ghc-9.4.8\eta-service-0.1.0.0-K0aOwEi25BS9pYwtd4gwNr

library-dirs:
    C:\Users\HP\Desktop\Ride_Dispatch\eta_service\.stack-work\install\c84bbe0f\lib\x86_64-windows-ghc-9.4.8\eta-service-0.1.0.0-K0aOwEi25BS9pYwtd4gwNr
    C:\Users\HP\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\HP\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

library-dirs-static:
    C:\Users\HP\Desktop\Ride_Dispatch\eta_service\.stack-work\install\c84bbe0f\lib\x86_64-windows-ghc-9.4.8\eta-service-0.1.0.0-K0aOwEi25BS9pYwtd4gwNr
    C:\Users\HP\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\HP\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

dynamic-library-dirs:
    C:\Users\HP\Desktop\Ride_Dispatch\eta_service\.stack-work\install\c84bbe0f\lib\x86_64-windows-ghc-9.4.8
    C:\Users\HP\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\HP\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

data-dir:
    C:\Users\HP\Desktop\Ride_Dispatch\eta_service\.stack-work\install\c84bbe0f\share\x86_64-windows-ghc-9.4.8\eta-service-0.1.0.0

hs-libraries:         HSeta-service-0.1.0.0-K0aOwEi25BS9pYwtd4gwNr
include-dirs:
    C:\Users\HP\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\include

depends:
    aeson-2.1.2.1-BAtHMIdFRzCCNr8B5pvdUZ base-4.17.2.1
    scotty-0.12.1-8Ba9tSjoJ0681VjHBJUYAC text-2.0.2

haddock-interfaces:
    C:\Users\HP\Desktop\Ride_Dispatch\eta_service\.stack-work\install\c84bbe0f\doc\eta-service-0.1.0.0\eta-service.haddock

haddock-html:
    C:\Users\HP\Desktop\Ride_Dispatch\eta_service\.stack-work\install\c84bbe0f\doc\eta-service-0.1.0.0
